### Dowmload and install dependency "pycoingecko"

In [3]:
from openpyxl.styles.builtins import title
!pip3 install pycoingecko

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pycoingecko in /Users/sam/Library/Python/3.9/lib/python/site-packages (3.2.0)
Requirement already satisfied: requests in /Users/sam/Library/Python/3.9/lib/python/site-packages (from pycoingecko) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/sam/Library/Python/3.9/lib/python/site-packages (from requests->pycoingecko) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /Users/sam/Library/Python/3.9/lib/python/site-packages (from requests->pycoingecko) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/sam/Library/Python/3.9/lib/python/site-packages (from requests->pycoingecko) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/sam/Library/Python/3.9/lib/python/site-packages (from requests->pycoingecko) (2026.2.25)

##### Import libraries
##### create api obj and
##### get 30 days coin chart data by id : _bitcoin_

In [4]:
from pycoingecko import CoinGeckoAPI
import pandas as pd
cg = CoinGeckoAPI()
bitcoin_data = cg.get_coin_market_chart_by_id(id = 'bitcoin', vs_currency = 'usd', days=20,)
bit_df = pd.DataFrame.from_dict(bitcoin_data)
print(bitcoin_data)

/Users/sam/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

{'prices': [[1773306166481, 69873.54699369983], [1773309740654, 69965.12439910452], [1773313399983, 70410.776313674], [1773316898333, 70446.04864493353], [1773320510956, 70394.17441967604], [1773324165636, 69946.98958100153], [1773327808867, 69573.44808855272], [1773331207779, 70350.70557737058], [1773334950091, 70400.86986115224], [1773338615909, 70219.81853454876], [1773342126349, 69831.65145548187], [1773345732896, 70478.88551994674], [1773349406992, 70197.5330839794], [1773352938352, 70310.98344617597], [1773356594705, 70168.7542773972], [1773360173734, 70495.67568002958], [1773363796593, 71485.14595298373], [1773367350292, 71636.02077745824], [1773371027841, 71157.29995548744], [1773374592528, 71402.44699242084], [1773378113727, 71332.35527407174], [1773381645270, 71605.42850767514], [1773385278545, 71347.22352973108], [1773388977579, 71626.30716984723], [1773392547777, 71790.51173955765], [1773396196581, 72039.91429367974], [1773399772290, 72479.00197278638], [1773403443677, 72257.33355590506], [1773407004672, 72811.1463390778], [1773410537333, 73479.76604347788], [1773414169516, 72418.40119283782], [1773417748239, 71826.53239420471], [1773421398651, 71929.65397808861], [1773425011564, 71008.47076387439], [1773428591761, 71073.13309572938], [1773432200902, 71182.3833483821], [1773435741903, 71352.08921401051], [1773439350036, 71143.18410708023], [1773442982093, 70794.09447352387], [1773446619476, 70965.28228600459], [1773450211794, 70689.05192245601], [1773453610025, 70859.84174916545], [1773457351714, 70856.08993041962], [1773460959969, 71077.08880135501], [1773464518710, 71039.20366424312], [1773468187350, 71011.29320098588], [1773471806121, 70652.39350585645], [1773475396648, 70601.52304011412], [1773479010974, 70580.5484855447], [1773482553681, 70539.27343461686], [1773486099301, 70555.90077748458], [1773489729942, 70714.59815430894], [1773493361591, 70724.35668141994], [1773496990096, 70882.7823514032], [1773500588054, 70619.8198143914], [1773504125968, 70602.17423220258], [1773507782262, 70685.12450447425], [1773511355626, 70618.0223290148], [1773514930070, 70690.04718025915], [1773518540311, 70703.14031485881], [1773522009193, 70835.17460900525], [1773525746460, 70809.74343130055], [1773529401480, 70723.78060432566], [1773533259142, 71122.93561633487], [1773536927997, 71019.85971523909], [1773540500452, 71163.18010932418], [1773544297154, 71448.55927020362], [1773547778581, 71426.78461210527], [1773551380663, 71540.16542807396], [1773554985701, 71576.92630814361], [1773558574815, 71454.95959793388], [1773561776214, 71449.02334070223], [1773565339862, 71636.44609377658], [1773568922266, 71827.47727845323], [1773572561431, 71796.90292372422], [1773576147633, 71849.26834156351], [1773579684571, 71616.49549145128], [1773583311895, 71557.56740824718], [1773586910344, 71609.51482757785], [1773590635496, 71491.25288274372], [1773594221424, 71430.56399292653], [1773597784172, 71831.06725444554], [1773601339141, 71389.64804785485], [1773604897994, 71557.0448250269], [1773608571828, 71760.88018765219], [1773612187978, 72080.43829377418], [1773615834901, 72783.28669635301], [1773619420268, 72799.1789981442], [1773622930253, 72560.01961161768], [1773626591578, 72753.6500288425], [1773630202681, 72565.34143373226], [1773633808360, 73658.22913876995], [1773637401214, 73861.95608107506], [1773640882934, 74157.34241148319], [1773644632344, 73765.32077429206], [1773648201713, 73485.98723788554], [1773651804789, 73138.3743773866], [1773655310788, 73259.31973150831], [1773658942142, 73734.91279332073], [1773662561875, 73565.81170904198], [1773666166420, 73843.3241538607], [1773669715209, 74019.4070913728], [1773673358863, 73446.1842039846], [1773676903512, 73263.87882074014], [1773680532829, 73764.83336285164], [1773684144088, 73954.17488339139], [1773687780568, 73957.40834188467], [1773691372241, 73958.31193466885], [1773694819595, 74225.21989199621], [1773698623788, 74438.82965717503], [1773702050286, 74717.3894011731], [1773705638551, 74858.14870100339], [1773709355180, 75173.14226779129], [1773712958672, 75632.41015615774], [1773716628546, 75197.44389538407], [1773720193275, 74426.47726466598], [1773723761559, 74279.50516740244], [1773727410176, 74004.71341039937], [1773730883760, 74080.28999363363], [1773734610257, 74251.47017440872], [1773738165765, 74187.08468542341], [1773741770920, 73931.42869131609], [1773745379217, 73727.01590319516], [1773749041536, 74049.99025292388], [1773752404364, 73716.49902404359], [1773756121391, 73664.92688506791], [1773759765350, 74372.31505154063], [1773763410001, 73938.45954892249], [1773766987725, 74139.84966600154], [1773770626983, 74522.97781759078], [1773774170119, 74686.02993457245], [1773777744229, 74511.43757475897], [1773781392981, 74556.97200158171], [1773784968723, 74690.90770773192], [1773788566201, 74313.11694423317], [1773792181062, 73926.27899152413], [1773795782976, 73854.96886976], [1773799373606, 74092.38831657296], [1773802990508, 74358.62022555566], [1773806412761, 74494.67471958217], [1773810055674, 74179.81973580908], [1773813749134, 73946.73033688653], [1773817433029, 73961.87566925112], [1773820983231, 73890.21271622225], [1773824567001, 74036.09311491044], [1773828174518, 74163.78094501335], [1773831777859, 73939.52246684712], [1773835386573, 72953.72917602796], [1773838829830, 72387.28689365885], [1773842587741, 72067.40252497199], [1773846170135, 71297.85643495581], [1773849738360, 71518.80469283315], [1773853350113, 71328.61409583432], [1773856932278, 71626.30657689057], [1773860634328, 71026.62449466846], [1773864179243, 71074.61890935857], [1773867766070, 71238.10852868533], [1773871212632, 71292.59033537445], [1773874972451, 71136.52376150078], [1773878574421, 71256.65956041873], [1773882221975, 70995.49208200075], [1773885748019, 71140.22164960648], [1773889417086, 71052.20965877775], [1773892943097, 71225.15940712935], [1773896640928, 70844.73985109958], [1773900151569, 70830.7659487663], [1773903641841, 70551.5551160704], [1773907246552, 70212.66707442794], [1773910841605, 69971.39660037315], [1773914582005, 70492.22671693734], [1773918185773, 70125.92304238673], [1773921612416, 69934.93151927635], [1773925312904, 69298.87894108835], [1773928998452, 69891.65869108934], [1773932565270, 69550.63011862883], [1773936161830, 69454.08947590156], [1773939734705, 69446.04133014526], [1773943280111, 69849.44114340031], [1773946888461, 69818.76001818525], [1773950475027, 70284.79229992839], [1773954091143, 70491.5688120522], [1773957733786, 70472.29443555106], [1773961392665, 70147.45290782927], [1773964953623, 69912.32846307463], [1773968484282, 70219.72096303198], [1773972146061, 70426.94072356535], [1773975751861, 70435.78664589739], [1773979365249, 70741.66407362273], [1773982952298, 70772.03118023534], [1773986582763, 70574.84559253055], [1773990197343, 70485.67832017319], [1773993716348, 70852.16480880113], [1773997217157, 71037.67359152887], [1774000989371, 70559.11237019852], [1774004572336, 70593.94372748287], [1774008139928, 70454.22833072978], [1774011766902, 70314.35277681354], [1774015381935, 69863.08791396998], [1774018959855, 69739.70808468577], [1774022589200, 69824.36946411383], [1774026226438, 69848.23738975245], [1774029795951, 69922.80531197492], [1774033402166, 69731.46429879949], [1774036966274, 70138.7419088915], [1774040604070, 70036.79676847711], [1774044123509, 70525.66120992822], [1774047774633, 70781.08357698002], [1774051244247, 70511.00634700106], [1774054920626, 70683.13082950574], [1774058521755, 70476.00823266465], [1774062130543, 70717.09908340046], [1774065694320, 70681.3117368], [1774069368847, 70633.26137500843], [1774073291213, 70715.81221084928], [1774076821171, 70743.5837097416], [1774080362765, 70690.39129587835], [1774083755171, 70582.04532292718], [1774087479250, 70643.73195218536], [1774091090480, 70586.03151380002], [1774094644816, 70635.87177138265], [1774098231910, 70705.52326221105], [1774101878273, 70722.73585326485], [1774105255748, 70590.52579726202], [1774109036838, 70642.8192357941], [1774112458035, 70287.02223502546], [1774116298389, 70312.70512781104], [1774119955596, 70407.76826144295], [1774123396225, 70377.09842445592], [1774126820253, 70447.53457913788], [1774130627860, 70340.289645773], [1774134202603, 70292.26388186325], [1774137944520, 68412.67504146349], [1774141204248, 68897.26755616778], [1774145062478, 68943.09325322721], [1774148646477, 69304.79718965513], [1774152188127, 69329.99728279315], [1774155827146, 69320.00160322535], [1774159402229, 69141.59971807108], [1774162985897, 69146.84716615826], [1774166622369, 68908.16957877796], [1774170256860, 68795.5505642291], [1774173800891, 68817.53435389008], [1774177390944, 68653.9970738177], [1774181039071, 68211.08116857347], [1774184485142, 68651.18982923409], [1774188084242, 68722.96325302527], [1774191770081, 68698.62007881168], [1774195350607, 68821.70886419388], [1774198951599, 68813.30024858509], [1774202608917, 68704.73553817421], [1774206009569, 68572.35892748222], [1774209608644, 68181.20471380129], [1774213420720, 68179.84748181398], [1774216974774, 67836.00655868028], [1774220523024, 68296.86295861873], [1774224204479, 67848.87605821833], [1774227759135, 67684.18004265723], [1774231345842, 67914.62164219593], [1774234921857, 68291.62334548199], [1774238519904, 68061.75633105007], [1774242110399, 68505.55527490156], [1774245736176, 68856.33114252616], [1774249310693, 67813.61163802224], [1774252948385, 68302.02880878812], [1774256533964, 68433.41999646043], [1774260169610, 68248.65909045594], [1774263780576, 68533.56691669108], [1774267376980, 70090.85625395848], [1774270951406, 70658.89681764365], [1774274597746, 71413.47363715255], [1774278207114, 71453.46560478497], [1774281794826, 70123.74223304595], [1774285419326, 70539.95075755077], [1774289023051, 71069.34533324269], [1774292633045, 71049.75201776822], [1774296266620, 70673.84328686942], [1774299816033, 70898.50990542116], [1774303408929, 70871.49537193075], [1774307025953, 70754.11294097341], [1774310581550, 70892.82823994374], [1774314191859, 70691.20963441042], [1774317773654, 70497.783796673], [1774321226282, 70429.82090509095], [1774324973422, 70505.5355628202], [1774328617094, 70367.86749397316], [1774332095299, 70252.45308411747], [1774335726833, 70502.13562095199], [1774339306399, 71285.55416417253], [1774342894519, 70926.05228348031], [1774346477550, 71299.66799821133], [1774350100911, 71237.84222578786], [1774353713259, 71110.07805777165], [1774357314402, 70930.59887301897], [1774360878048, 70039.64380544117], [1774364513516, 69903.3681889646], [1774368104685, 69872.59897269034], [1774371698079, 69442.96978741302], [1774375299369, 69179.35721667454], [1774378859322, 69417.88017389276], [1774382512338, 69296.70386159363], [1774386070241, 70036.29129693768], [1774389695855, 70259.23587427003], [1774393302313, 70327.56965564], [1774396901189, 70524.51175942823], [1774400477409, 70847.88845384026], [1774404116680, 70709.04546672574], [1774407721664, 70485.95261570862], [1774411297522, 70696.82035952818], [1774414916714, 70916.77984389212], [1774418407649, 71082.75166729843], [1774422052573, 71012.75095282859], [1774425681741, 70899.66539633296], [1774429249017, 71240.60340405164], [1774432879756, 71326.31988743633], [1774436545739, 71494.83039503878], [1774440151946, 71651.03014324601], [1774443737052, 71682.98549923916], [1774447372972, 71631.72227038858], [1774450945657, 71291.00953905468], [1774454511937, 70843.14037566936], [1774458215970, 71310.27596792881], [1774461768127, 70743.12969322263], [1774465413507, 70762.88522631538], [1774468999649, 70803.52212386463], [1774472626701, 70982.1484301469], [1774476009804, 71003.3810189207], [1774479784847, 71343.12285014275], [1774483393778, 71309.26403856269], [1774486957036, 71235.418543699], [1774490537196, 71245.79769201373], [1774494256276, 70866.96468821711], [1774497802041, 70865.83284704047], [1774501223783, 70754.14022016643], [1774505012766, 69976.52473870447], [1774508579937, 70065.39506348], [1774512136009, 70060.46802946102], [1774515725228, 69983.71047448418], [1774519325496, 69565.28302289729], [1774522962155, 69461.64056489215], [1774526576387, 69258.38692240322], [1774530160282, 69416.11164790414], [1774533744361, 69530.43000475917], [1774537429908, 69462.818723659], [1774540929547, 69052.36668187703], [1774544545087, 68886.05755073845], [1774548124516, 68460.0405580777], [1774551824798, 68432.89019563152], [1774555353024, 68575.61619653407], [1774558982668, 68949.5314813283], [1774562504418, 68888.27500980144], [1774566177028, 68826.30686850422], [1774569713681, 68791.11093800364], [1774573321307, 68712.98514161636], [1774576918450, 68987.91604743515], [1774580550629, 68861.18343940613], [1774584105099, 68732.87385203048], [1774587610314, 68544.83136866611], [1774591342784, 68584.57619715178], [1774594952479, 68614.73543266914], [1774598541043, 68433.29595166513], [1774602128660, 67896.72261998236], [1774605725619, 67666.10383727407], [1774609352756, 66462.11327811745], [1774612878669, 66666.3731870575], [1774616517509, 66589.48462775366], [1774620157380, 66110.91859349872], [1774623672138, 66166.55253010265], [1774627301235, 66084.9735136777], [1774630911354, 65931.436380254], [1774634553036, 65604.15370696093], [1774638116668, 65817.95817627014], [1774641715474, 66036.20502233546], [1774645269262, 65978.7624110396], [1774648898706, 66021.45792444395], [1774652422388, 65981.97377183192], [1774656108123, 66327.66737271791], [1774659725818, 66382.83249898783], [1774663307482, 66067.46482722324], [1774666933976, 65995.96577262062], [1774670473119, 66167.61183329132], [1774674103758, 66189.65590146254], [1774677770598, 66307.09909195548], [1774681361612, 66363.77341122921], [1774684971907, 66516.27378317354], [1774688564620, 66350.41976637962], [1774692183789, 66263.63211704824], [1774695755027, 66178.92986536778], [1774699350566, 66303.92808472476], [1774702959960, 66415.83889333812], [1774706563374, 66770.2554659786], [1774710134949, 66707.15373392777], [1774713701933, 66946.6353317456], [1774717340045, 66874.77753331588], [1774720848596, 66803.07998327093], [1774724499985, 66879.95377021199], [1774728020090, 66851.141718053], [1774731726850, 66894.75795554336], [1774735329384, 66645.1518328983], [1774738933564, 66694.139781946], [1774742442590, 66321.06539994745], [1774746121074, 66412.9505268756], [1774749618934, 66521.48936569078], [1774753403935, 66735.3884387065], [1774756928014, 66860.30574313855], [1774760651134, 66683.71289085437], [1774764148603, 66741.21981768549], [1774767653805, 66688.62043170675], [1774771427213, 66630.82888015691], [1774774960670, 66674.97448070651], [1774778601069, 66581.35073321467], [1774782072480, 66469.4796184686], [1774785788212, 66774.32162975357], [1774789314842, 66794.30316085815], [1774792883439, 66517.1597689279], [1774796616208, 66517.29275887285], [1774800208904, 66466.44058378502], [1774803755729, 66444.45410400286], [1774807419550, 66331.62463090713], [1774810958133, 66375.06666880092], [1774814536313, 66284.482768732], [1774818142563, 66546.10792505798], [1774821754238, 66674.76525877648], [1774825352382, 65813.3236524164], [1774828966299, 65970.42899513361], [1774832567800, 66252.8557606698], [1774836027641, 66578.9309952134], [1774839749868, 67070.37991749584], [1774843372251, 67111.63131687373], [1774846918078, 67548.59321993159], [1774850609452, 67461.9195301119], [1774854136845, 67274.14216754284], [1774857734241, 67516.1458614326], [1774861309311, 67616.6140366827], [1774864935200, 67448.61317843373], [1774868602929, 67434.17090680324], [1774872166388, 67590.41657666316], [1774875791854, 67850.83361908437], [1774879346157, 67454.49103166346], [1774882937858, 67732.65929264908], [1774886539611, 67565.83141885296], [1774890137414, 67262.04727463868], [1774893775845, 66753.13370588605], [1774897379069, 66555.3785781471], [1774900934310, 66432.346364874], [1774904400111, 66587.99024414114], [1774908115394, 66757.19246041842], [1774911754488, 66734.19561943135], [1774915251658, 66699.27436893585], [1774918959095, 67091.7699360093], [1774922593465, 67930.29873609915], [1774926188705, 67945.39135718174], [1774929752591, 67646.52741376395], [1774933217262, 67488.81448012279], [1774937014045, 67618.1466100619], [1774940587902, 67449.74316002423], [1774944127622, 67299.23356164555], [1774947710854, 66756.23307911558], [1774951351685, 66037.9769355128], [1774954965003, 66302.74182544308], [1774958568819, 66620.01251485397], [1774962125102, 66608.17879412256], [1774965761238, 67163.45267766963], [1774969215473, 66558.38670829509], [1774972935280, 66698.35856220762], [1774976553066, 67542.07857770176], [1774980130393, 67395.06167693074], [1774983739613, 67721.57727071697], [1774987363718, 67762.72263907967], [1774990800135, 68136.90158842586], [1774994551087, 68196.60422235407], [1774998192739, 68146.94856232416], [1775001767897, 68231.32977209098], [1775005402355, 68223.70211409187], [1775008973680, 67741.61626889415], [1775012531509, 67581.86166020094], [1775016003908, 68067.62035882538], [1775019806624, 68224.37632532336], [1775023328753, 68401.93752431103], [1775027037397, 69101.02455101817], [1775030542800, 68646.2153927601], [1775031265000, 68562.86921786932]], 'market_caps': [[1773306166481, 1397233857386.686], [1773309740654, 1399378762519.8008], [1773313399983, 1408771433160.1533], [1773316898333, 1408853808960.4817], [1773320510956, 1407968806132.9175], [1773324165636, 1397774768735.3613], [1773327808867, 1389997179395.678], [1773331207779, 1407847431897.823], [1773334950091, 1408403121849.4094], [1773338615909, 1404499949687.9565], [1773342126349, 1398192808484.6318], [1773345732896, 1409961042276.3562], [1773349406992, 1403836160467.1946], [1773352938352, 1406640386737.1504], [1773356594705, 1402591041436.837], [1773360173734, 1409873668559.5356], [1773363796593, 1427661784420.3687], [1773367350292, 1432971506673.3606], [1773371027841, 1422843138598.941], [1773374592528, 1428033214129.673], [1773378113727, 1426789581214.5784], [1773381645270, 1432170975607.4954], [1773385278545, 1427213235748.9163], [1773388977579, 1431089513854.7554], [1773392547777, 1436285037610.4338], [1773396196581, 1440769815541.548], [1773399772290, 1449016673887.712], [1773403443677, 1446017154381.7456], [1773407004672, 1455603471663.4612], [1773410537333, 1469690620221.5562], [1773414169516, 1450579890390.7803], [1773417748239, 1436647150178.7617], [1773421398651, 1439106060383.2625], [1773425011564, 1420151642752.4084], [1773428591761, 1421925743806.1519], [1773432200902, 1424583422089.1243], [1773435741903, 1427637396831.264], [1773439350036, 1423388365650.956], [1773442982093, 1416035171073.1396], [1773446619476, 1419133420991.5525], [1773450211794, 1413783248790.4685], [1773453610025, 1417218304021.1995], [1773457351714, 1417319597080.5408], [1773460959969, 1421638367662.247], [1773464518710, 1421986733823.5574], [1773468187350, 1420267135128.4854], [1773471806121, 1413556108805.4773], [1773475396648, 1412071630337.9087], [1773479010974, 1411719555129.819], [1773482553681, 1410764169065.9333], [1773486099301, 1411393384713.3528], [1773489729942, 1414346522276.768], [1773493361591, 1415141756569.4136], [1773496990096, 1417380955407.3918], [1773500588054, 1413201400141.5745], [1773504125968, 1412182515777.3806], [1773507782262, 1414097469247.1895], [1773511355626, 1412385540007.9832], [1773514930070, 1413578249811.247], [1773518540311, 1414186665488.7297], [1773522009193, 1416944841832.3586], [1773525746460, 1415948674745.092], [1773529401480, 1414546706262.025], [1773533259142, 1422842296957.1416], [1773536927997, 1420516115921.22], [1773540500452, 1424307646919.437], [1773544297154, 1429064305644.262], [1773547778581, 1427269960008.8054], [1773551380663, 1431113216480.9795], [1773554985701, 1430281469030.0752], [1773558574815, 1429329926629.4587], [1773561776214, 1428876940094.253], [1773565339862, 1432890489511.9082], [1773568922266, 1436723121989.5376], [1773572561431, 143636


##### Select only prices of bitcoins

In [5]:
bitcoin_data['prices']

[[1773306166481, 69873.54699369983],
 [1773309740654, 69965.12439910452],
 [1773313399983, 70410.776313674],
 [1773316898333, 70446.04864493353],
 [1773320510956, 70394.17441967604],
 [1773324165636, 69946.98958100153],
 [1773327808867, 69573.44808855272],
 [1773331207779, 70350.70557737058],
 [1773334950091, 70400.86986115224],
 [1773338615909, 70219.81853454876],
 [1773342126349, 69831.65145548187],
 [1773345732896, 70478.88551994674],
 [1773349406992, 70197.5330839794],
 [1773352938352, 70310.98344617597],
 [1773356594705, 70168.7542773972],
 [1773360173734, 70495.67568002958],
 [1773363796593, 71485.14595298373],
 [1773367350292, 71636.02077745824],
 [1773371027841, 71157.29995548744],
 [1773374592528, 71402.44699242084],
 [1773378113727, 71332.35527407174],
 [1773381645270, 71605.42850767514],
 [1773385278545, 71347.22352973108],
 [1773388977579, 71626.30716984723],
 [1773392547777, 71790.51173955765],
 [1773396196581, 72039.91429367974],
 [1773399772290, 72479.00197278638],
 [1773403443677, 72257.33355590506],
 [1773407004672, 72811.1463390778],
 [1773410537333, 73479.76604347788],
 [1773414169516, 72418.40119283782],
 [1773417748239, 71826.53239420471],
 [1773421398651, 71929.65397808861],
 [1773425011564, 71008.47076387439],
 [1773428591761, 71073.13309572938],
 [1773432200902, 71182.3833483821],
 [1773435741903, 71352.08921401051],
 [1773439350036, 71143.18410708023],
 [1773442982093, 70794.09447352387],
 [1773446619476, 70965.28228600459],
 [1773450211794, 70689.05192245601],
 [1773453610025, 70859.84174916545],
 [1773457351714, 70856.08993041962],
 [1773460959969, 71077.08880135501],
 [1773464518710, 71039.20366424312],
 [1773468187350, 71011.29320098588],
 [1773471806121, 70652.39350585645],
 [1773475396648, 70601.52304011412],
 [1773479010974, 70580.5484855447],
 [1773482553681, 70539.27343461686],
 [1773486099301, 70555.90077748458],
 [1773489729942, 70714.59815430894],
 [1773493361591, 70724.35668141994],
 [1773496990096, 70882.7823514032],
 [1773500588054, 70619.8198143914],
 [1773504125968, 70602.17423220258],
 [1773507782262, 70685.12450447425],
 [1773511355626, 70618.0223290148],
 [1773514930070, 70690.04718025915],
 [1773518540311, 70703.14031485881],
 [1773522009193, 70835.17460900525],
 [1773525746460, 70809.74343130055],
 [1773529401480, 70723.78060432566],
 [1773533259142, 71122.93561633487],
 [1773536927997, 71019.85971523909],
 [1773540500452, 71163.18010932418],
 [1773544297154, 71448.55927020362],
 [1773547778581, 71426.78461210527],
 [1773551380663, 71540.16542807396],
 [1773554985701, 71576.92630814361],
 [1773558574815, 71454.95959793388],
 [1773561776214, 71449.02334070223],
 [1773565339862, 71636.44609377658],
 [1773568922266, 71827.47727845323],
 [1773572561431, 71796.90292372422],
 [1773576147633, 71849.26834156351],
 [1773579684571, 71616.49549145128],
 [1773583311895, 71557.56740824718],
 [1773586910344, 71609.51482757785],
 [1773590635496, 71491.25288274372],
 [1773594221424, 71430.56399292653],
 [1773597784172, 71831.06725444554],
 [1773601339141, 71389.64804785485],
 [1773604897994, 71557.0448250269],
 [1773608571828, 71760.88018765219],
 [1773612187978, 72080.43829377418],
 [1773615834901, 72783.28669635301],
 [1773619420268, 72799.1789981442],
 [1773622930253, 72560.01961161768],
 [1773626591578, 72753.6500288425],
 [1773630202681, 72565.34143373226],
 [1773633808360, 73658.22913876995],
 [1773637401214, 73861.95608107506],
 [1773640882934, 74157.34241148319],
 [1773644632344, 73765.32077429206],
 [1773648201713, 73485.98723788554],
 [1773651804789, 73138.3743773866],
 [1773655310788, 73259.31973150831],
 [1773658942142, 73734.91279332073],
 [1773662561875, 73565.81170904198],
 [1773666166420, 73843.3241538607],
 [1773669715209, 74019.4070913728],
 [1773673358863, 73446.1842039846],
 [1773676903512, 73263.87882074014],
 [1773680532829, 73764.83336285164],
 [1773684144088, 73954.17488339139],
 [1773687780568, 73957.40834188467],
 [1773691372241, 73958.31193466885],
 [1773694819595, 74225.21989199621],
 [1773698623788, 74438.82965717503],
 [1773702050286, 74717.3894011731],
 [1773705638551, 74858.14870100339],
 [1773709355180, 75173.14226779129],
 [1773712958672, 75632.41015615774],
 [1773716628546, 75197.44389538407],
 [1773720193275, 74426.47726466598],
 [1773723761559, 74279.50516740244],
 [1773727410176, 74004.71341039937],
 [1773730883760, 74080.28999363363],
 [1773734610257, 74251.47017440872],
 [1773738165765, 74187.08468542341],
 [1773741770920, 73931.42869131609],
 [1773745379217, 73727.01590319516],
 [1773749041536, 74049.99025292388],
 [1773752404364, 73716.49902404359],
 [1773756121391, 73664.92688506791],
 [1773759765350, 74372.31505154063],
 [1773763410001, 73938.45954892249],
 [1773766987725, 74139.84966600154],
 [1773770626983, 74522.97781759078],
 [1773774170119, 74686.02993457245],
 [1773777744229, 74511.43757475897],
 [1773781392981, 74556.97200158171],
 [1773784968723, 74690.90770773192],
 [1773788566201, 74313.11694423317],
 [1773792181062, 73926.27899152413],
 [1773795782976, 73854.96886976],
 [1773799373606, 74092.38831657296],
 [1773802990508, 74358.62022555566],
 [1773806412761, 74494.67471958217],
 [1773810055674, 74179.81973580908],
 [1773813749134, 73946.73033688653],
 [1773817433029, 73961.87566925112],
 [1773820983231, 73890.21271622225],
 [1773824567001, 74036.09311491044],
 [1773828174518, 74163.78094501335],
 [1773831777859, 73939.52246684712],
 [1773835386573, 72953.72917602796],
 [1773838829830, 72387.28689365885],
 [1773842587741, 72067.40252497199],
 [1773846170135, 71297.85643495581],
 [1773849738360, 71518.80469283315],
 [1773853350113, 71328.61409583432],
 [1773856932278, 71626.30657689057],
 [1773860634328, 71026.62449466846],
 [1773864179243, 71074.61890935857],
 [1773867766070, 71238.10852868533],
 [1773871212632, 71292.59033537445],
 [1773874972451, 71136.52376150078],
 [1773878574421, 71256.65956041873],
 [1773882221975, 70995.49208200075],
 [1773885748019, 71140.22164960648],
 [1773889417086, 71052.20965877775],
 [1773892943097, 71225.15940712935],
 [1773896640928, 70844.73985109958],
 [1773900151569, 70830.7659487663],
 [1773903641841, 70551.5551160704],
 [1773907246552, 70212.66707442794],
 [1773910841605, 69971.39660037315],
 [1773914582005, 70492.22671693734],
 [1773918185773, 70125.92304238673],
 [1773921612416, 69934.93151927635],
 [1773925312904, 69298.87894108835],
 [1773928998452, 69891.65869108934],
 [1773932565270, 69550.63011862883],
 [1773936161830, 69454.08947590156],
 [1773939734705, 69446.04133014526],
 [1773943280111, 69849.44114340031],
 [1773946888461, 69818.76001818525],
 [1773950475027, 70284.79229992839],
 [1773954091143, 70491.5688120522],
 [1773957733786, 70472.29443555106],
 [1773961392665, 70147.45290782927],
 [1773964953623, 69912.32846307463],
 [1773968484282, 70219.72096303198],
 [1773972146061, 70426.94072356535],
 [1773975751861, 70435.78664589739],
 [1773979365249, 70741.66407362273],
 [1773982952298, 70772.03118023534],
 [1773986582763, 70574.84559253055],
 [1773990197343, 70485.67832017319],
 [1773993716348, 70852.16480880113],
 [1773997217157, 71037.67359152887],
 [1774000989371, 70559.11237019852],
 [1774004572336, 70593.94372748287],
 [1774008139928, 70454.22833072978],
 [1774011766902, 70314.35277681354],
 [1774015381935, 69863.08791396998],
 [1774018959855, 69739.70808468577],
 [1774022589200, 69824.36946411383],
 [1774026226438, 69848.23738975245],
 [1774029795951, 69922.80531197492],
 [1774033402166, 69731.46429879949],
 [1774036966274, 70138.7419088915],
 [1774040604070, 70036.79676847711],
 [1774044123509, 70525.66120992822],
 [1774047774633, 70781.08357698002],
 [1774051244247, 70511.00634700106],
 [1774054920626, 70683.13082950574],
 [1774058521755, 70476.00823266465],
 [1774062130543, 70717.09908340046],
 [1774065694320, 70681.3117368],
 [1774069368847, 70633.26137500843],
 [1774073291213, 70715.81221084928],
 [1774076821171, 70743.5837097416],
 [1774080362765, 70690.39129587835],
 [1774083755171, 70582.04532292718],
 [1774087479250, 70643.73195218536],
 [1774091090480, 70586.03151380002],
 [1774094644816, 70635.87177138265],
 [1774098231910, 70705.52326221105],
 [1774101878273, 70722.73585326485],
 [1774105255748, 70590.52579726202],
 [1774109036838, 70642.8192357941],
 [1774112458035, 70287.02223502546],
 [1774116298389, 70312.70512781104],
 [1774119955596, 70407.76826144295],
 [1774123396225, 70377.09842445592],
 [1774126820253, 70447.53457913788],
 [1774130627860, 70340.289645773],
 [1774134202603, 70292.26388186325],
 [1774137944520, 68412.67504146349],
 [1774141204248, 68897.26755616778],
 [1774145062478, 68943.09325322721],
 [1774148646477, 69304.79718965513],
 [1774152188127, 69329.99728279315],
 [1774155827146, 69320.00160322535],
 [1774159402229, 69141.59971807108],
 [1774162985897, 69146.84716615826],
 [1774166622369, 68908.16957877796],
 [1774170256860, 68795.5505642291],
 [1774173800891, 68817.53435389008],
 [1774177390944, 68653.9970738177],
 [1774181039071, 68211.08116857347],
 [1774184485142, 68651.18982923409],
 [1774188084242, 68722.96325302527],
 [1774191770081, 68698.62007881168],
 [1774195350607, 68821.70886419388],
 [1774198951599, 68813.30024858509],
 [1774202608917, 68704.73553817421],
 [1774206009569, 68572.35892748222],
 [1774209608644, 68181.20471380129],
 [1774213420720, 68179.84748181398],
 [1774216974774, 67836.00655868028],
 [1774220523024, 68296.86295861873],
 [1774224204479, 67848.87605821833],
 [1774227759135, 67684.18004265723],
 [1774231345842, 67914.62164219593],
 [1774234921857, 68291.62334548199],
 [1774238519904, 68061.75633105007],
 [1774242110399, 68505.55527490156],
 [1774245736176, 68856.33114252616],
 [1774249310693, 67813.61163802224],
 [1774252948385, 68302.02880878812],
 [1774256533964, 68433.41999646043],
 [1774260169610, 68248.65909045594],
 [1774263780576, 68533.56691669108],
 [1774267376980, 70090.85625395848],
 [1774270951406, 70658.89681764365],
 [1774274597746, 71413.47363715255],
 [1774278207114, 71453.46560478497],
 [1774281794826, 70123.74223304595],
 [1774285419326, 70539.95075755077],
 [1774289023051, 71069.34533324269],
 [1774292633045, 71049.75201776822],
 [1774296266620, 70673.84328686942],
 [1774299816033, 70898.50990542116],
 [1774303408929, 70871.49537193075],
 [1774307025953, 70754.11294097341],
 [1774310581550, 70892.82823994374],
 [1774314191859, 70691.20963441042],
 [1774317773654, 70497.783796673],
 [1774321226282, 70429.82090509095],
 [1774324973422, 70505.5355628202],
 [1774328617094, 70367.86749397316],
 [1774332095299, 70252.45308411747],
 [1774335726833, 70502.13562095199],
 [1774339306399, 71285.55416417253],
 [1774342894519, 70926.05228348031],
 [1774346477550, 71299.66799821133],
 [1774350100911, 71237.84222578786],
 [1774353713259, 71110.07805777165],
 [1774357314402, 70930.59887301897],
 [1774360878048, 70039.64380544117],
 [1774364513516, 69903.3681889646],
 [1774368104685, 69872.59897269034],
 [1774371698079, 69442.96978741302],
 [1774375299369, 69179.35721667454],
 [1774378859322, 69417.88017389276],
 [1774382512338, 69296.70386159363],
 [1774386070241, 70036.29129693768],
 [1774389695855, 70259.23587427003],
 [1774393302313, 70327.56965564],
 [1774396901189, 70524.51175942823],
 [1774400477409, 70847.88845384026],
 [1774404116680, 70709.04546672574],
 [1774407721664, 70485.95261570862],
 [1774411297522, 70696.82035952818],
 [1774414916714, 70916.77984389212],
 [1774418407649, 71082.75166729843],
 [1774422052573, 71012.75095282859],
 [1774425681741, 70899.66539633296],
 [1774429249017, 71240.60340405164],
 [1774432879756, 71326.31988743633],
 [1774436545739, 71494.83039503878],
 [1774440151946, 71651.03014324601],
 [1774443737052, 71682.98549923916],
 [1774447372972, 71631.72227038858],
 [1774450945657, 71291.00953905468],
 [1774454511937, 70843.14037566936],
 [1774458215970, 71310.27596792881],
 [1774461768127, 70743.12969322263],
 [1774465413507, 70762.88522631538],
 [1774468999649, 70803.52212386463],
 [1774472626701, 70982.1484301469],
 [1774476009804, 71003.3810189207],
 [1774479784847, 71343.12285014275],
 [1774483393778, 71309.26403856269],
 [1774486957036, 71235.418543699],
 [1774490537196, 71245.79769201373],
 [1774494256276, 70866.96468821711],
 [1774497802041, 70865.83284704047],
 [1774501223783, 70754.14022016643],
 [1774505012766, 69976.52473870447],
 [1774508579937, 70065.39506348],
 [1774512136009, 70060.46802946102],
 [1774515725228, 69983.71047448418],
 [1774519325496, 69565.28302289729],
 [1774522962155, 69461.64056489215],
 [1774526576387, 69258.38692240322],
 [1774530160282, 69416.11164790414],
 [1774533744361, 69530.43000475917],
 [1774537429908, 69462.818723659],
 [1774540929547, 69052.36668187703],
 [1774544545087, 68886.05755073845],
 [1774548124516, 68460.0405580777],
 [1774551824798, 68432.89019563152],
 [1774555353024, 68575.61619653407],
 [1774558982668, 68949.5314813283],
 [1774562504418, 68888.27500980144],
 [1774566177028, 68826.30686850422],
 [1774569713681, 68791.11093800364],
 [1774573321307, 68712.98514161636],
 [1774576918450, 68987.91604743515],
 [1774580550629, 68861.18343940613],
 [1774584105099, 68732.87385203048],
 [1774587610314, 68544.83136866611],
 [1774591342784, 68584.57619715178],
 [1774594952479, 68614.73543266914],
 [1774598541043, 68433.29595166513],
 [1774602128660, 67896.72261998236],
 [1774605725619, 67666.10383727407],
 [1774609352756, 66462.11327811745],
 [1774612878669, 66666.3731870575],
 [1774616517509, 66589.48462775366],
 [1774620157380, 66110.91859349872],
 [1774623672138, 66166.55253010265],
 [1774627301235, 66084.9735136777],
 [1774630911354, 65931.436380254],
 [1774634553036, 65604.15370696093],
 [1774638116668, 65817.95817627014],
 [1774641715474, 66036.20502233546],
 [1774645269262, 65978.7624110396],
 [1774648898706, 66021.45792444395],
 [1774652422388, 65981.97377183192],
 [1774656108123, 66327.66737271791],
 [1774659725818, 66382.83249898783],
 [1774663307482, 66067.46482722324],
 [1774666933976, 65995.96577262062],
 [1774670473119, 66167.61183329132],
 [1774674103758, 66189.65590146254],
 [1774677770598, 66307.09909195548],
 [1774681361612, 66363.77341122921],
 [1774684971907, 66516.27378317354],
 [1774688564620, 66350.41976637962],
 [1774692183789, 66263.63211704824],
 [1774695755027, 66178.92986536778],
 [1774699350566, 66303.92808472476],
 [1774702959960, 66415.83889333812],
 [1774706563374, 66770.2554659786],
 [1774710134949, 66707.15373392777],
 [1774713701933, 66946.6353317456],
 [1774717340045, 66874.77753331588],
 [1774720848596, 66803.07998327093],
 [1774724499985, 66879.95377021199],
 [1774728020090, 66851.141718053],
 [1774731726850, 66894.75795554336],
 [1774735329384, 66645.1518328983],
 [1774738933564, 66694.139781946],
 [1774742442590, 66321.06539994745],
 [1774746121074, 66412.9505268756],
 [1774749618934, 66521.48936569078],
 [1774753403935, 66735.3884387065],
 [1774756928014, 66860.30574313855],
 [1774760651134, 66683.71289085437],
 [1774764148603, 66741.21981768549],
 [1774767653805, 66688.62043170675],
 [1774771427213, 66630.82888015691],
 [1774774960670, 66674.97448070651],
 [1774778601069, 66581.35073321467],
 [1774782072480, 66469.4796184686],
 [1774785788212, 66774.32162975357],
 [1774789314842, 66794.30316085815],
 [1774792883439, 66517.1597689279],
 [1774796616208, 66517.29275887285],
 [1774800208904, 66466.44058378502],
 [1774803755729, 66444.45410400286],
 [1774807419550, 66331.62463090713],
 [1774810958133, 66375.06666880092],
 [1774814536313, 66284.482768732],
 [1774818142563, 66546.10792505798],
 [1774821754238, 66674.76525877648],
 [1774825352382, 65813.3236524164],
 [1774828966299, 65970.42899513361],
 [1774832567800, 66252.8557606698],
 [1774836027641, 66578.9309952134],
 [1774839749868, 67070.37991749584],
 [1774843372251, 67111.63131687373],
 [1774846918078, 67548.59321993159],
 [1774850609452, 67461.9195301119],
 [1774854136845, 67274.14216754284],
 [1774857734241, 67516.1458614326],
 [1774861309311, 67616.6140366827],
 [1774864935200, 67448.61317843373],
 [1774868602929, 67434.17090680324],
 [1774872166388, 67590.41657666316],
 [1774875791854, 67850.83361908437],
 [1774879346157, 67454.49103166346],
 [1774882937858, 67732.65929264908],
 [1774886539611, 67565.83141885296],
 [1774890137414, 67262.04727463868],
 [1774893775845, 66753.13370588605],
 [1774897379069, 66555.3785781471],
 [1774900934310, 66432.346364874],
 [1774904400111, 66587.99024414114],
 [1774908115394, 66757.19246041842],
 [1774911754488, 66734.19561943135],
 [1774915251658, 66699.27436893585],
 [1774918959095, 67091.7699360093],
 [1774922593465, 67930.29873609915],
 [1774926188705, 67945.39135718174],
 [1774929752591, 67646.52741376395],
 [1774933217262, 67488.81448012279],
 [1774937014045, 67618.1466100619],
 [1774940587902, 67449.74316002423],
 [1774944127622, 67299.23356164555],
 [1774947710854, 66756.23307911558],
 [1774951351685, 66037.9769355128],
 [1774954965003, 66302.74182544308],
 [1774958568819, 66620.01251485397],
 [1774962125102, 66608.17879412256],
 [1774965761238, 67163.45267766963],
 [1774969215473, 66558.38670829509],
 [1774972935280, 66698.35856220762],
 [1774976553066, 67542.07857770176],
 [1774980130393, 67395.06167693074],
 [1774983739613, 67721.57727071697],
 [1774987363718, 67762.72263907967],
 [1774990800135, 68136.90158842586],
 [1774994551087, 68196.60422235407],
 [1774998192739, 68146.94856232416],
 [1775001767897, 68231.32977209098],
 [1775005402355, 68223.70211409187],
 [1775008973680, 67741.61626889415],
 [1775012531509, 67581.86166020094],
 [1775016003908, 68067.62035882538],
 [1775019806624, 68224.37632532336],
 [1775023328753, 68401.93752431103],
 [1775027037397, 69101.02455101817],
 [1775030542800, 68646.2153927601],
 [1775031265000, 68562.86921786932]]

##### Convert into dataframe

In [6]:

bit_df = pd.DataFrame(bitcoin_data['prices'], columns=['TimeStamp', 'price'])
bit_df

         TimeStamp         price
0    1773306166481  69873.546994
1    1773309740654  69965.124399
2    1773313399983  70410.776314
3    1773316898333  70446.048645
4    1773320510956  70394.174420
..             ...           ...
476  1775019806624  68224.376325
477  1775023328753  68401.937524
478  1775027037397  69101.024551
479  1775030542800  68646.215393
480  1775031265000  68562.869218

[481 rows x 2 columns]

##### Convert timestamp into readable format

In [7]:
bit_df['Date'] = pd.to_datetime(bit_df['TimeStamp'], unit='ms')
bit_df

         TimeStamp         price                    Date
0    1773306166481  69873.546994 2026-03-12 09:02:46.481
1    1773309740654  69965.124399 2026-03-12 10:02:20.654
2    1773313399983  70410.776314 2026-03-12 11:03:19.983
3    1773316898333  70446.048645 2026-03-12 12:01:38.333
4    1773320510956  70394.174420 2026-03-12 13:01:50.956
..             ...           ...                     ...
476  1775019806624  68224.376325 2026-04-01 05:03:26.624
477  1775023328753  68401.937524 2026-04-01 06:02:08.753
478  1775027037397  69101.024551 2026-04-01 07:03:57.397
479  1775030542800  68646.215393 2026-04-01 08:02:22.800
480  1775031265000  68562.869218 2026-04-01 08:14:25.000

[481 rows x 3 columns]

### Ploting CandleSticks

In [8]:
candlestick_data = bit_df.groupby(bit_df.Date.dt.date).agg({'price': ['min', 'max', 'first', 'last']})
candlestick_data

                   price
                     min           max         first          last
Date
2026-03-12  69573.448089  70478.885520  69873.546994  70168.754277
2026-03-13  70495.675680  73479.766043  70495.675680  70794.094474
2026-03-14  70539.273435  71077.088801  70965.282286  70723.780604
2026-03-15  71019.859715  72783.286696  71122.935616  72783.286696
2026-03-16  72560.019612  74717.389401  72799.178998  74717.389401
2026-03-17  73664.926885  75632.410156  74858.148701  74313.116944
2026-03-18  71026.624495  74494.674720  73926.278992  71136.523762
2026-03-19  69298.878941  71256.659560  71256.659560  70147.452908
2026-03-20  69731.464299  71037.673592  69912.328463  70781.083577
2026-03-21  70287.022235  70743.583710  70511.006347  70292.263882
2026-03-22  67836.006559  69329.997283  68412.675041  68296.862959
2026-03-23  67684.180043  71453.465605  67848.876058  70754.112941
2026-03-24  69179.357217  71299.667998  70892.828240  70327.569656
2026-03-25  70485.952616  71682.985499  70524.511759  71343.122850
2026-03-26  68432.890196  71309.264039  71309.264039  68826.306869
2026-03-27  65604.153707  68987.916047  68791.110938  65981.973772
2026-03-28  65995.965773  66946.635332  66327.667373  66694.139782
2026-03-29  65813.323652  66860.305743  66321.065400  65813.323652
2026-03-30  65970.428995  67850.833619  65970.428995  66734.195619
2026-03-31  66037.976936  68196.604222  66699.274369  68146.948562
2026-04-01  67581.861660  69101.024551  68231.329772  68562.869218

#### Use Plotly to render candles

In [9]:
# download plotly and install
!pip3 install plotly

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in /Users/sam/Library/Python/3.9/lib/python/site-packages (6.6.0)
Requirement already satisfied: narwhals>=1.15.1 in /Users/sam/Library/Python/3.9/lib/python/site-packages (from plotly) (2.18.1)
Requirement already satisfied: packaging in /Users/sam/Library/Python/3.9/lib/python/site-packages (from plotly) (26.0)

In [10]:

import plotly.graph_objects as go
import plotly
fig = go.Figure(data=[go.Candlestick(x = candlestick_data.index,
                                           open= candlestick_data['price']['first'],
                                           high= candlestick_data['price']['max'],
                                           low= candlestick_data['price']['min'],
                                           close = candlestick_data['price']['last']
                                           )])
fig.update_layout(xaxis_rangeslider_visible=False, xaxis_title='Date', yaxis_title='Price $(USD)', title= 'Bitcoin Candlestick for 20 days')

plotly.offline.plot(fig, filename='./bitcoin_candlestick.html',)

'./bitcoin_candlestick.html'